config/routes.rb
Rails.application.routes.draw do
  get    'tasks',          to: 'tasks#index'

  get    'tasks/new',      to: 'tasks#new'
  post   'tasks',          to: 'tasks#create'

  # NB: The `show` route needs to be *after* `new` route.
  get    'tasks/:id',      to: 'tasks#show', as: :task

  get    'tasks/:id/edit', to: 'tasks#edit'
  patch  'tasks/:id',      to: 'tasks#update'

  delete 'tasks/:id',      to: 'tasks#destroy', as: :delete
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  #READ ALL
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new #Afficher la tache
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/create.html.erb
<div class="container">
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>
</div>

app/views/tasks/destroy.html.erb
<div class="container">
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/delete.html.erb</p>

<%= link_to "Delete", task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
</div>

app/views/tasks/edit.html.erb
<div class="container">
<h1>Edit a Task</h1>

<%= form_for(@task) do |t| %>
  <div class="form-group">
    <%= t.label :title %>
    <%= t.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= t.label :details %>
    <%= t.text_field :details, class: 'form-control' %>
  </div>

  <%= t.submit 'Update task', class: 'btn btn-primary' %>
<% end %>
</div>

app/views/tasks/index.html.erb
<div class="container">
<h1>My Tasks</h1>

<% @tasks.each do |task| %>
  <% if task.completed == true %>
    <li>
      <h2><input type="checkbox" name="task" id="checkbox" checked> <%= link_to task.title, task_path(task) %> <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, delete_path(task.id), method: :delete, data: { confirm: "Are you sure?" } %></h2>
    </li>
  <% else %>
    <li>
      <h2><input type="checkbox" name="task" id="checkbox"> <%= link_to task.title, task_path(task) %> <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, delete_path(task.id), method: :delete, data: { confirm: "Are you sure?" } %></h2>
    </li>
  <% end %>
<% end %>

<div class="back-link">
  <%=link_to tasks_new_path do %>
    <i class="fas fa-plus"></i>
    Add a new task
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="container">
<h1>New Task</h1>

<%= form_for(@task) do |t| %>
  <div class="form-group">
    <%= t.label :title %>
    <%= t.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= t.label :details %>
    <%= t.text_field :details, class: 'form-control' %>
  </div>

  <%= t.submit class: 'btn btn-primary'  %>
<% end %>
</div>

app/views/tasks/show.html.erb
<div class="container">
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<% if @task.completed == true %>
    <li>
      <p><input type="checkbox" name="task" id="checkbox" checked> This task is completed</p>
    </li>
  <% else %>
    <li>
      <p><input type="checkbox" id="checkbox"> This task is not completed yet</p>
    </li>
  <% end %>

<div class="back-link">
  <%=link_to tasks_path do %>
    <i class="fas fa-undo-alt"></i>
    Back to list
  <% end %>
</div>

</div>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>